include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    non_constant_identifier_names: false
    constant_identifier_names: false
    always_declare_return_types: false
    avoid_relative_lib_imports: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    use_string_buffers: true
    valid_regexps: true
