// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_Z-eOVU5_iyYwINBpHpVfsv5eFKVIzQ',
    appId: '1:788765359485:web:10344a40f210f786ce6014',
    messagingSenderId: '788765359485',
    projectId: 'clk-de7ae',
    authDomain: 'clk-de7ae.firebaseapp.com',
    storageBucket: 'clk-de7ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCit_juZrY3o-dR9YHYqSXEsx8O0yWTbjI',
    appId: '1:788765359485:android:d5a088a96d8714c1ce6014',
    messagingSenderId: '788765359485',
    projectId: 'clk-de7ae',
    storageBucket: 'clk-de7ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcxyfmWvlmHdyz5ed_QcJu1tWnZmVbrSU',
    appId: '1:788765359485:ios:20ce11efdecf4aa6ce6014',
    messagingSenderId: '788765359485',
    projectId: 'clk-de7ae',
    storageBucket: 'clk-de7ae.appspot.com',
    iosBundleId: 'com.example.clk',
  );
}
